apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ghcr-auth
spec:
  externalSecretName: ghcr-auth
  refreshTime: 1h
  namespaceSelector:
    matchLabels:
      cloudsteak.io/ghcr-auth: "true"
  externalSecretSpec:
    refreshInterval: 24h
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: ghcr-auth
      template:
        type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: /prod/shared/ghcr-auth
          property: .dockerconfigjson
