apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evolvia-backend-core-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    environment: production
    app: evolvia-backend
    component: backend-core
    type: secrets
spec:
  project: cloudmentor
  destination:
    server: https://kubernetes.default.svc
    namespace: evolvia-backend-prod

  source:
    repoURL: https://github.com/cloudsteak/cm-companion
    targetRevision: main
    path: apps/production/evolvia-backend/components/evolvia-backend-core/manifests

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
