apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cm-messenger-secret-app
  namespace: cm-messenger-prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cm-messenger-secret-app
  data:
    - secretKey: BREVO_API_KEY
      remoteRef:
        key: /prod/app/cm-messenger/brevo-api-key
        property: BREVO_API_KEY
