apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cm-messenger-credentials
  namespace: cm-messenger-prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cm-messenger-credentials
  data:
    - secretKey: BREVO_API_KEY
      remoteRef:
        key: /prod/app/cm-messenger/credentials
        property: BREVO_API_KEY
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: /prod/app/cm-messenger/credentials
        property: INTERNAL_MESSENGER_API_KEY
