apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evolvia-backend-namespace-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Namespace should be created first
  labels:
    environment: production
    type: namespace
    app: evolvia-backend
spec:
  project: cloudmentor
  source:
    repoURL: https://github.com/cloudsteak/cm-companion
    targetRevision: main
    path: apps/production/evolvia-backend/components/namespace/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: evolvia-backend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
