image:
  repository: ghcr.io/cloudsteak/cm-messenger
  tag: "0.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

configmap:
  LOG_LEVEL: "INFO"
  EMAIL_SENDER: "noreply@evolvia.hu"
  EMAIL_SENDER_NAME: "Evolvia"
  PORTAL_AZURE_URL: "https://portal.azure.com"
  PORTAL_AWS_URL: "https://console.aws.amazon.com"

# Keep internal API key disabled (no auth)
secretInternal:
  enabled: false

# GHCR image pull auth
imagePullSecrets:
  enabled: true
  name: ghcr-auth
