apiVersion: v1
kind: ConfigMap
metadata:
  name: evolvia-backend-core-config
  namespace: evolvia-backend-prod
data:
  LOG_LEVEL: ""
  REDIS_HOST: ""
  REDIS_PORT: ""
  REDIS_DB: ""
  AUTH0_ALGORITHMS: ""
  GITHUB_REPO: ""
  GITHUB_WORKFLOW_FILENAME: ""
  WORDPRESS_WEBHOOK_URL: ""
  MESSENGER_HOST: ""
  MESSENGER_PATH: ""
  MESSENGER_TEMPLATE: ""
  VERIFY_LAB_HOST: ""
  VERIFY_LAB_PATH: ""
