apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: evolvia-backend-core-credentials
  namespace: evolvia-backend-prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: evolvia-backend-core-credentials
  data:
    - secretKey: AUTH0_DOMAIN
      remoteRef:
        key: /prod/app/evolvia-backend-core/credentials
        property: auth0.domain
    - secretKey: AUTH0_AUDIENCE
      remoteRef:
        key: /prod/app/evolvia-backend-core/credentials
        property: auth0.audience
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: /prod/app/evolvia-backend-core/credentials
        property: github.token
    - secretKey: WORDPRESS_SECRET_KEY
      remoteRef:
        key: /prod/app/evolvia-backend-core/credentials
        property: wordpress.secret_key
    - secretKey: INTERNAL_SECRET
      remoteRef:
        key: /prod/app/evolvia-backend-core/credentials
        property: security.internal_secret
    - secretKey: INTERNAL_MESSENGER_API_KEY
      remoteRef:
        key: /prod/app/evolvia-backend-core/credentials
        property: security.internal_messenger_api_key
    - secretKey: INTERNAL_VERIFY_API_KEY
      remoteRef:
        key: /prod/app/evolvia-backend-core/credentials
        property: security.internal_verify_api_key
