apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: evolvia-verify-lab-secret
  namespace: evolvia-backend-prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: evolvia-verify-lab-secret
  data:
    - secretKey: AZURE_SUBSCRIPTION_ID
      remoteRef:
        key: /prod/app/evolvia-verify-lab/credentials
        property: azure.subscription_id
    - secretKey: AZURE_TENANT_ID
      remoteRef:
        key: /prod/app/evolvia-verify-lab/credentials
        property: azure.tenant_id
    - secretKey: AZURE_CLIENT_ID
      remoteRef:
        key: /prod/app/evolvia-verify-lab/credentials
        property: azure.client_id
    - secretKey: AZURE_CLIENT_SECRET
      remoteRef:
        key: /prod/app/evolvia-verify-lab/credentials
        property: azure.client_secret
    - secretKey: INTERNAL_VERIFY_API_KEY
      remoteRef:
        key: /prod/app/evolvia-verify-lab/credentials
        property: security.internal_api_key
