apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cm-messenger-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    environment: production
    app: cm-messenger
    type: secrets
spec:
  project: cloudmentor
  destination:
    server: https://kubernetes.default.svc
    namespace: cm-messenger-prod

  source:
    repoURL: https://github.com/cloudsteak/cm-companion
    targetRevision: main
    path: apps/production/cm-messenger/components/secrets/manifests

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
