namespace:
  name: evolvia-backend-prod

image:
  repository: ghcr.io/cloudsteak/evolvia-verify-lab
  tag: "0.0.1"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

config:
  LOG_LEVEL: INFO

imagePullSecrets:
  enabled: true
  name: ghcr-auth

probes:
  periodSeconds: 10
